* Useful Commands

  - helm-occur
  - helm-show-kill-ring
  - completion-at-point
  - which-key-show-top-level
  - yank-rectangle
    kill in multiple-cursor and get out of it, then yank, it'll
    only yank the kill-ring from main cursor. If you want to yank
    all, use this command (C-x r y)
  - shell-command
  - run-python
  - python-shell-send-region
  - python-shell-send-defun
  - python-shell-send-buffer
  - python-shell-send-file

* Lessons Learned

** vterm

   The following commands are what I was trying to have a good
   =vterm-module= to make =vterm= working.

   First, when I was typing the command =M-x vterm=, the Emacs showed
   me this message:

   =Vterm needs `vterm-module' to work.  Compile it now? (y or n)=

   I click 'y' to proceed, then message showed again for another error:

   =Vterm needs CMake to be compiled. Please, install CMake=

   So I jumped into the terminal and type these command to install
   dependent tools (see [[https://github.com/akermu/emacs-libvterm#requirements][akermu/emacs-libvterm]]):

   #+begin_src shell
   brew install cmake
   brew install libvterm
   brew install --build-from-source perl
   #+end_src

   Note: I'm not sure whether the =perl= is mandatory.

   But I still got the same message complaining about no =CMake= at all.

   Finally I stumbled onto this [[https://github.com/akermu/emacs-libvterm/issues/169][thread]] and found that I have to build
   =vterm-module= by myself on terminal:

   #+begin_src shell
   cd ~/.emacs.d/elpa/vterm-20210217.737
   mkdir -p build
   cd build
   cmake ..
   make
   #+end_src

   Then =vterm= worked!
